spring.application.name=common-yh

spring.mail.host=smtpdm.aliyun.com
spring.mail.port=465
spring.mail.username=steam@94746424.xyz
spring.mail.password=BDFqq123ww
spring.mail.default-encoding=UTF-8

# SSL ?????SpringBoot 3.x ??????
spring.mail.properties.mail.transport.protocol=smtps
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.ssl.enable=true
spring.mail.properties.mail.smtps.timeout=10000