
# ==============================================
# ??????
# ==============================================
spring.application.name=User-trade  # ??? Nacos ???????
server.port=8081
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# ==============================================
# ??????????????
# ==============================================
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/YHtrade?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=your-very-long-custom-key-must-be-at-least-256-bits-12345678901234567890123456789012
jwt.expiration=36000000000

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=commontrade.usertrade.entity

spring.mail.host=smtpdm.aliyun.com
spring.mail.port=465
spring.mail.username=yuehua@94746424.xyz
spring.mail.password=BDFqq123ww
spring.mail.default-encoding=UTF-8

# ??????????????
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0

# ??????????????
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0